Improved logic to determine resource models in a spec
dsgouda/autorest pull request #3
Opened 2017-03-16 00:29 UTC by dsgouda

- Addresses issue https://github.com/Azure/autorest/issues/1936
- Added tests to check for valid resource models

@veronicagg @vishrutshah @sarangan12 FYI

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
>          public static bool IsTrackedResource(Schema schema, Dictionary<string, Schema> definitions)
I assume this function is to be replaced/removed when the new logic is final? :)

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // Get all models that are returned by PUT operations (200 response)
warning: I'll be super picky, mainly because I want to understand the *precise* definition of all this myself :-D

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // Get all models that are returned by PUT operations (200 response)
this section corresponds to category 1 of Veronica's comment, right? if so, there is a slight mismatch: you are only considering the 200 response models, while there is no such restriction in her definition (note that she talks about 200 in category 2, but not category 1) - so either the definition, or this implementation is slightly off (and I have no clue which)

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var getOperationsResponseModels = GetResponseModelDefinitions(serviceDefinition);
this doesn't only retrieve the response models of `GET`s, does it? to be honest, I'd obtain those models right here (inline):
- it's basically the code from above (`get` instead of `put`, this time the 200 part is according to Veronica's specification)
- more importantly: I can see us modify `GetResponseModelDefinitions` ("hey, why doesn't this method also return 20x models? let's add that!") and accidentally break this code...

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                            defPair.Value.Extensions?.ContainsKey("x-ms-azure-resource") == true &&
another case for the `Get`/`GetValue` (not sure which it was) extension method ;-)
=> `defPair.Value.Extensions?.GetValue("x-ms-azure-resource") == true`

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // set of base resource models is the union of all three aboce
the attack of the typo: aboce

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            foreach (var modelName in serviceDefinition.Definitions.Keys)
hold on - I thought the spec was describing exactly what resources are, but this code returns all models that have one of the above as a *base class*? either the spec or my understanding of the spec or this is wrong :-D

In other words: After reading the spec ("Resources list should be built as the union of ...") I expected this method to simply return `putResponseModelNames.Union(modelsAllOfOnResource).Union(xmsAzureResourceModels)`

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                if (UrlResRegEx.IsMatch(item.Reference))
I'd convert this into `return UrlResRegEx... || IsAllOf...` (one could also LINQ the entire loop, but I'd almost not unless the expression turns out to be super readable)

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static bool IsAllOfOnResourceTypeModel(string modelName, Dictionary<string, Schema> definitions, IEnumerable<string> baseResourceModels)
as I'm not sure why we need this method at all (see earlier comment), I see some common functionality: "does X have an allOf (transitively) on Y". Once Y is the `Resource` model, another time (here) it's a list of some models, but both those cases would be a one-liner using such a method.

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsLocationProperty(resModel, definitions));
sweet

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        /// For a given set of resource models evaluates which models are tracked and returns those
whoops

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var modelSchema = definitions[modelName];
hmmm looking at this method, maybe what we really want is a "give me *all* `allOf`s (transitively) of model X". Then once can simply check for "does X have an allOf on Y", but one can also implement this method here trivially

I'm just concerned about all the common logic, e.g. for getting a model definition:
- Here you do `if (string.IsNullOrEmpty(modelName) || !definitions.ContainsKey(modelName))`
- the 2 times before it's `if (!definitions.ContainsKey(modelName))`

much duplication!

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.ResourceModels = ValidationUtilities.GetResourceModels(serviceDefinition);
the attack of the C# monster! since you are (if I didn't miss anything) consistently using `IEnumerable` (a good thing per se), evaluation of these 3 lists will be lazy. That *not only* means they will only be computed when someone actually loops over, say, `ProxyResourceModels`, it *also* means it will be *recomputed* every time you do that. In this specific case, I'd append `.ToList()` to each of these 3 assignments, that'll "materialize" the lists once and for all :-)

2017-03-16 01:56 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            foreach (var modelName in serviceDefinition.Definitions.Keys)
looking at it again, maybe there is a confusion regarding category 3: there Veronica says, that not the models containing `x-ms-azure-resource` *themselves* are a resource, but that models that have such a model as base class are a resource - so `xmsAzureResourceModels` does not represent category 3. it seems to me as if you apply the part that is missing for category 3 to *all* categories (I mean `putResponseModelNames` and `modelsAllOfOnResource` are already perfectly fine and *do* represent category 1 and 2, right?)

2017-03-16 17:41 UTC, vishrutshah requested changes

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // Get all models that are returned by PUT operations (200 response)
I believe that we only consider models returned in 200 for PUT so we need to update category 1 to be accurate.

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
Doesn't `ContainsKey("200")` already returns bool ? If so we should avoid ==true check

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
minor: In general I'd prefer "Strongly typed variable" then `var` It helps in F12 and reading.

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putResponseModelNames = putOperations.Select(op => op.Responses["200"]?.Schema?.Reference?.StripDefinitionPath()).Where(modelName => !string.IsNullOrEmpty(modelName));
minor: Please format the doc so that it can be consistent. Ex: line 47 has `op=>op.Responses` while line 48 has `op => Responses`

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                            defPair.Value.Extensions?.ContainsKey("x-ms-azure-resource") == true &&
Does `ContainsKey` return `bool`?

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static bool IsAllOfOnModelNamedResource(string modelName, Dictionary<string, Schema> definitions)
Is this supposed to be used outside? `public`. I am asking because if so I'd add simple Argument null checks on modelName and definitions as well.

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            if (modelSchema.AllOf?.Any() != true) return false;
Does `Any()` returns `bool`?

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static bool IsAllOfOnResourceTypeModel(string modelName, Dictionary<string, Schema> definitions, IEnumerable<string> baseResourceModels)
similar question on `public` - visibility of this method

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            if (definitions[modelName]?.AllOf?.Any() != true) return false;
`Any()` ?

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // there is separate check to weed out resources which
Just curious: Is it possible to move those weed out logic inside?

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            if (string.IsNullOrEmpty(modelName) || !definitions.ContainsKey(modelName)) return false;
I'd prefer `NullOrWhiteSpace` over `NullOrEmpty` all the places

2017-03-16 17:41 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +
minor: unnecessary blank lines

2017-03-16 18:16 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
>          public static bool IsTrackedResource(Schema schema, Dictionary<string, Schema> definitions)
Yes, that is the final goal here, kept it as is since current validation rules are referencing it

2017-03-16 18:24 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var getOperationsResponseModels = GetResponseModelDefinitions(serviceDefinition);
You're a visionary 😃

2017-03-16 23:31 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
The expression evaluates to ```bool?``` hence the explicit check

2017-03-16 23:31 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
var makes the code more readable especially for long variable types

2017-03-16 23:31 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                            defPair.Value.Extensions?.ContainsKey("x-ms-azure-resource") == true &&
It can return a ```bool``` or a ```null```

2017-03-16 23:35 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            if (modelSchema.AllOf?.Any() != true) return false;
The expression can return a ```bool``` or a ```null```

---
In reply to: [106478373](https://github.com/dsgouda/autorest/pull/3#discussion_r106478373) [](ancestors = 106478373)

2017-03-17 00:09 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
@vishrutshah F12 works on var and hovering also reveals the full type ;-) ...in Visual Studio, that is, not sure about VSCode

2017-03-17 03:48 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperations = GetOperationsByRequestMethod("put", serviceDefinition).Where(op=>op.Responses?.ContainsKey("200")==true);
Cool. that makes sense then :)

2017-03-17 21:58 UTC, vishrutshah requested changes

2017-03-17 21:58 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
@veronicagg and I was talking about this and seems like we need to also check for `location` being a `required` property for this to be `TrackedResourceModel`.

2017-03-17 21:58 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.ResourceModels = parent?.ResourceModels;
We were also discussing this. We think that "ResourceModels" is a virtual/computed set. In that case we should not have that as a property but a function that gives union of `TrackedResourceModels ` & `ProxyResourceModels ` what do you think as model can either be Tracked or Proxy.

2017-03-17 22:00 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
Intentionally left this condition relaxed since we won't be able to catch already defined resource models otherwise.

2017-03-17 22:02 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.ResourceModels = parent?.ResourceModels;
I don't think I follow. The whole idea behind sticking these as properties was to eliminate recalculating the resource models for every single rule that requires it. A function won't be ideal for it.

2017-03-17 22:36 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.ResourceModels = parent?.ResourceModels;
So i am saying that ResourceModels = TrackedResourceModels + ProxyResourceModels. If so your method `GetResourceModels` should be `GetTrackedResources().Union(GetProxyResources())`.

I relooked at the code and seems like you are computing Proxy from Resources and Tracked. That's totally fine.

So my question would be `ResourceModels` are not really 100% `ResourceModels` they are `PotentialResourceModels`. Is my understanding right or did i miss something?

2017-03-17 22:37 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
So does that mean these set of PotentialResourceModel can have candidates those are not categorized as either Tracked or Proxy?

2017-03-17 22:53 UTC, veronicagg requested changes

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            putOperationsResponseModels = putOperationsResponseModels.Where(putRespModel => ContainsProperties(putRespModel, serviceDefinition.Definitions, new List<string>() { "id", "name", "type"})
@ravbhatnagar should we be applying this restriction on the properties? I'm asking because we did not write this on the whiteboard the other day.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        /// Checks whether a model definition has the properties "id, name and type" (which are "Resource" type properties)
comment doesn't look to reflect the operation, operation seems more generic than what's written here.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        /// anywhere in its heirarchy
typo heirarchy -> hierarchy, please find/replace all instances of the word

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            // Get all models that are returned by PUT operations (200 response)
@ravbhatnagar, @amarzavery I think we need to look into 200 or 201, not just 200.
We did not write this condition on the board, but it can make sense to look for success terminal status responses, I just don't want to miss potential valid codes.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperationsResponseModels = GetOperationResponseModels("put", serviceDefinition).Except(xmsAzureResourceModels);
if someone set x-ms-azure-resource again on a model that inherits from Resource, I think we would be excluding the model, which I don't think is correct. @ravbhatnagar, could you confirm? There may be a need of another rule that checks whether x-ms-resource is 'only' used in the base class, not sure if this is a violation; and not sure what SDK generation would do if x-ms-azure-resource is set to true more than once in the hierarchy - @amarzavery, do you know?.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var getOperationsResponseModels = GetOperationResponseModels("get", serviceDefinition).Except(xmsAzureResourceModels);
similar question here on the except "xmsAzureResourceModels"

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var getOperationsResponseModels = GetOperationResponseModels("get", serviceDefinition).Except(xmsAzureResourceModels);
in this case we do want only 200 responses, which is what's happening in the current code, but wanted to add a comment since you're sharing the method, and I commented before on adding more error codes.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            getOperationsResponseModels = getOperationsResponseModels.Where(putRespModel => ContainsProperties(putRespModel, serviceDefinition.Definitions, new List<string>() { "id", "name", "type"})
why are we checking on the properties? (same question as above)

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                getOperationsResponseModels.Where(modelName => serviceDefinition.Definitions.ContainsKey(modelName))
could this condition not be true serviceDefinition.Definitions.ContainsKey(modelName) at this point in the code? aren't we getting the model names from the definitions?

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            foreach (var modelRef in definitions[modelName].AllOf.Select(allofModel => allofModel.Reference?.StripDefinitionPath()).Where(allOfModel => !string.IsNullOrEmpty(allOfModel)))
could we have the linq query in a variable, that you reference in the foreach?

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            foreach (var modelRef in definitions[modelName].AllOf.Select(allofModel => allofModel.Reference?.StripDefinitionPath()).Where(allOfModel => !string.IsNullOrEmpty(allOfModel)))
could you explain/simplify this condition a bit? I'm not quite following what's going on here.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
location needs to be required for a "tracked resource"

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static IEnumerable<string> GetTrackedResources(IEnumerable<string> resourceModels, Dictionary<string, Schema> definitions)
not sure if we  "resourceModels" should be a parameter, for which we don't assert anything, to make sure it's a resource. This method in isolation, would categorize any models with location as Tracked Resource, right?
I'm wondering if the concept of "tracked" resource should be kept with the rule context, so tracked resource, is applying some extra conditions to the ResourceModels property.

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.TrackedResourceModels = parent?.ResourceModels;
why is TrackedResourceModels initialized to the same as ResourceModels?

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.TrackedResourceModels = parent?.ResourceModels;
what is this "RuleContext (parent) constructor used for?

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +        private void PopulateResourceTypes(ServiceDefinition serviceDefinition)
should we populate Tracked and Proxy resources, and provide a method that Resources as the union of the 2?

2017-03-17 22:53 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Validation/TrackedResourcePatchOperationValidation.cs
>                  if (respDefinitions.Contains(definition.Key) && ValidationUtilities.IsTrackedResource(definition.Value, definitions))
shouldn't tracked resource validation also be updated for this rule? is it tracked as part of another issue?

2017-03-17 22:55 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
If someone marks location as not required, it shouldn't be categorized as a tracked resource IMO. 
@ravbhatnagar can you confirm?

2017-03-17 23:04 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var putOperationsResponseModels = GetOperationResponseModels("put", serviceDefinition).Except(xmsAzureResourceModels);
note that even the "new" definition does not mention 200. Please synchronize on this!

2017-03-17 23:04 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            modelsAllOfOnXmsAzureResources = modelsAllOfOnXmsAzureResources.Where(modelName => serviceDefinition.Definitions.ContainsKey(modelName)
think this is missing the "name", "id", ... criterion

2017-03-17 23:04 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                            defPair.Value.Extensions?.ContainsKey("x-ms-azure-resource") == true &&
still not using `GetValue` extension method

2017-03-17 23:04 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var modelsAllOfOnResource =
never used... probably wanna use it for `resourceModels`. Also, make sure this set is disjoint from `putOperationsResponseModels`

2017-03-17 23:04 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            modelsAllOfOnXmsAzureResources = modelsAllOfOnXmsAzureResources.Where(modelName => serviceDefinition.Definitions.ContainsKey(modelName)
if I get the spec right, this criterion applies to *all* resources, right? if so, why not get those candidates *first* (I mean also spec it like that)?

2017-03-20 17:57 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            => resourceModels.Where(resModel => ContainsProperties(resModel, definitions, new List<string>() { "location" }));
for additional context please see https://github.com/Azure/autorest/issues/1861

2017-03-21 15:48 UTC, vishrutshah reviewed
Seems like you checked-in zip by mistake
`src/core/AutoRest/wonamecheck.zip`

2017-03-21 15:48 UTC, vishrutshah commented on src/modeler/AutoRest.Swagger.Tests/SwaggerModelerValidationTests.cs
> +            Assert.Equal(4, context.ResourceModels.Count());
You may want to check what are they exactly instead of numbers

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger.Tests/SwaggerModelerValidationTests.cs
> +            Assert.Equal(4, context.ResourceModels.Count());
Not sure I follow you here

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                            defPair.Value.Extensions?.ContainsKey("x-ms-azure-resource") == true &&
```GetValue``` forces me to typecast, and I'm not a fan of implicit casting, just a personal opinion though

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static IEnumerable<string> GetTrackedResources(IEnumerable<string> resourceModels, Dictionary<string, Schema> definitions)
Yes, this is set as a property for ```ContextRule``` too, is that what you're implying here.

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +            this.TrackedResourceModels = parent?.ResourceModels;
1. My bad, fixing it
2. Parent constructor is used to create the root ```ContextRule``` object which is constructed from a ```ServiceDefinition``` , other ```ContextRule``` objects can be created for different objects/levels within the ```ServiceDefinition```

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/Core/RuleContext.cs
> +        private void PopulateResourceTypes(ServiceDefinition serviceDefinition)
Like we discussed its easier to determine the overall resource models and tracked resources rather than proxy resources in isolation, hence this is the best way out.

2017-03-22 00:06 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/TrackedResourcePatchOperationValidation.cs
>                  if (respDefinitions.Contains(definition.Key) && ValidationUtilities.IsTrackedResource(definition.Value, definitions))
Yes, I'll post different PRs for all tracked resource related validation rules later

2017-03-22 17:58 UTC, veronicagg requested changes
few comments/questions rest looks good.

2017-03-22 17:58 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var modelsAllOfOnXmsAzureResources = serviceDefinition.Definitions.Keys.Except(resourceModels)
why is this check neeed "serviceDefinition.Definitions.ContainsKey(modelName)", would we ever have a model name that's not in the definitions?

2017-03-22 17:58 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
>          /// <returns>true if given model allOfs on given allOf list at any level of hierarchy</returns>
I'm a bit confused by the description of what the method does, could we make it more explanatory even if it's a little more verbose?

2017-03-22 17:58 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        /// <param name="allOfedModels">list of allOfed models</param>
could we explain what you mean by "allOfed" models?

2017-03-22 17:58 UTC, veronicagg commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        private static IEnumerable<string> EnumerateRequiredProperties(string modelName, Dictionary<string, Schema> definitions)
it would be nice if EnumerateProperties returned an IEnumerable of Properties, so this method could call "EnumerateProperties" and just have a condition on required for those? (similar comment for read only)

2017-03-23 03:19 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            putOperationsResponseModels = putOperationsResponseModels.Union(GetOperationResponseModels("put", serviceDefinition, "201").Except(xmsAzureResourceModels));
that `Except(xmsAzureResourceModels)` part is not reflected in https://github.com/Azure/autorest/issues/1936#issuecomment-288244278!
(also, it looks like this call could just be made *once* when assigning to `resourceModels`)

2017-03-23 03:19 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var modelsAllOfOnXmsAzureResources = serviceDefinition.Definitions.Keys.Except(resourceModels)
Category 3 of https://github.com/Azure/autorest/issues/1936#issuecomment-288244278 does not talk about allof!

2017-03-23 03:19 UTC, olydis commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static IEnumerable<string> EnumerateModelHierarchy(string modelName, Dictionary<string, Schema> definitions, IEnumerable<string> modelHierarchy = null)
this function is a little inside out: on the one hand, it's recursive and returns the list of models, on the other hand it gets such a list as a parameter? Think this entire method is
``` C#
public static IEnumerable<string> EnumerateModelHierarchy(string modelName, Dictionary<string, Schema> definitions) 
{
    IEnumerable<string> modelHierarchy = new [] { modelName };
    if (definitions.ContainsKey(modelName))
    {
        var allOfs = modelSchema.AllOf
            ?.Select(allOfSchema => allOfSchema.Reference?.StripDefinitionPath())
            .Where(modelRef => !string.IsNullOrEmpty(modelRef)) 
            ?? Enumerable.Empty<string>();
        modelHierarchy = modelHierarchy.Union(allOfs.SelectMany(allOf => EnumerateModelHierarchy(allOf, definitions)));
    }
    retun modelHierarchy;
} 
```

2017-03-23 19:13 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +            var modelsAllOfOnXmsAzureResources = serviceDefinition.Definitions.Keys.Except(resourceModels)
Sometimes, you gotta update the issue itself.

2017-03-23 21:09 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +        public static IEnumerable<string> EnumerateModelHierarchy(string modelName, Dictionary<string, Schema> definitions, IEnumerable<string> modelHierarchy = null)
Yes! this is exactly what I meant, got myself confused with mutability of the list objects.

2017-03-23 21:20 UTC, dsgouda commented
Reopening this PR against AutoRest master

2017-03-23 21:20 UTC, closed without merging