Tracked resource validation linter rules
dsgouda/autorest pull request #7
Opened 2017-03-27 21:12 UTC by sarangan12

@dsgouda @vishrutshah @veronicagg @salameer Please review and approve

2017-03-27 22:32 UTC, dsgouda requested changes
More comments on the way

2017-03-27 22:32 UTC, dsgouda commented on src/core/AutoRest.Core/Properties/Resources.resx
> +  <data name="TrackedResourcePropertiesValidation" xml:space="preserve">
How is this different than https://github.com/Azure/autorest/issues/1967

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ServiceDefinition.cs
> +        [Rule(typeof(TrackedResourceListByImmediateParent))]
Question: Are we checking for "ANY" of (list by immediate parent, list by resource group and list by subscriptions) or "ALL" of them

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                       regEx.IsMatch(operation.OperationId) &&
Simplify this a little
```getOperations.Where(op=>regEx.IsMatch(operation.OperationId) && ...).Any()```
Also, ValidationUtilities already has methods each to check for xmspageable and arraytype responses, please leverage those

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/DescriptionMissing.cs
> +                string key = definition.Key;
nit: Or you could simply say
```
if (string.IsNullOrWhiteSpace(definition.Value.Description))
{
          yield return new ValidationMessage(new FileObjectPath(context.File, context.Path), this, string.Format(ModelTypeFormatter, definition.Key));
}
```

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/DescriptiveDescriptionRequired.cs
> +    public class DescriptiveDescriptionRequired : DescriptionRequired<string>
So.... no IsValid or GetValidationMessages implementations here?

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/Extensions/LongRunningResponseValidationRule.cs
> +         public override string MessageTemplate => Resources.LongRunningResponseNotValid;
nit: format

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/OperationDescriptionRequired.cs
> +            return !string.IsNullOrWhiteSpace(entity?.Description);
At this point, ```entity``` cannot be null, so remove the ```?```

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/TrackedResourceGetOperationValidation.cs
> +                if (!getOperations.Any(op => op.Responses.ContainsKey("200") && (op.Responses["200"]?.Schema?.Reference?.StripDefinitionPath()).Equals(trackedResource)))
What if this ```op.Responses["200"]?.Schema?.Reference?.StripDefinitionPath()``` evaluates to null

2017-03-27 22:32 UTC, dsgouda commented on src/modeler/AutoRest.Swagger/Validation/TrackedResourceListByImmediateParent.cs
> +            Regex pathRegEx = new Regex("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/.+/.+/{.+}.*/" + childResource + "s$", RegexOptions.IgnoreCase);
Use this regex instead ```Subscriptions\/\{.+\}\/ResourceGroups\/\{.+\}\/providers\/([^\/]+)(?<typenamesandvalues>[^?]+)([\?]?.+)?```

2017-03-28 00:22 UTC, closed without merging

2017-03-28 21:19 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Validation/OperationDescriptionRequired.cs
> +            return !string.IsNullOrWhiteSpace(entity?.Description);
Done

2017-03-28 21:19 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Validation/Extensions/LongRunningResponseValidationRule.cs
> +         public override string MessageTemplate => Resources.LongRunningResponseNotValid;
Done

2017-03-28 21:20 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Validation/DescriptiveDescriptionRequired.cs
> +    public class DescriptiveDescriptionRequired : DescriptionRequired<string>
Yes. It is in the base class

2017-03-28 21:22 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Validation/DescriptionMissing.cs
> +                string key = definition.Key;
Done

2017-03-28 21:25 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Model/ValidationUtilities.cs
> +                       regEx.IsMatch(operation.OperationId) &&
Done

2017-03-28 21:27 UTC, sarangan12 commented on src/core/AutoRest.Core/Properties/Resources.resx
> +  <data name="TrackedResourcePropertiesValidation" xml:space="preserve">
Removed it

2017-03-28 21:29 UTC, sarangan12 commented on src/modeler/AutoRest.Swagger/Validation/TrackedResourceGetOperationValidation.cs
> +                if (!getOperations.Any(op => op.Responses.ContainsKey("200") && (op.Responses["200"]?.Schema?.Reference?.StripDefinitionPath()).Equals(trackedResource)))
redesigned it